const sampleJobs = [
    {
      title: "Software Engineer",
      shortDescription: "Join our team as a software engineer and work on cutting-edge projects.",
      longDescription: "As a software engineer at our company, you will have the opportunity to work on cutting-edge projects and play a key role in developing and maintaining our software solutions. You'll collaborate with a talented team of developers to create innovative software that meets our clients' needs. If you are passionate about coding and enjoy solving complex problems, we want you on our team.",
      type: "Full-time",
      department: "Engineering",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Marketing Specialist",
      shortDescription: "We are looking for a marketing specialist to help us promote our products.",
      longDescription: "Join our marketing team and take charge of promoting our products and services. As a marketing specialist, you will work on creating effective marketing campaigns, analyzing market trends, and identifying opportunities for brand growth. If you have a passion for marketing and want to make a significant impact, we'd love to have you on board.",
      type: "Part-time",
      department: "Marketing",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Sales Representative",
      shortDescription: "Sell our products and services to clients and help us grow our customer base.",
      longDescription: "If you're a dynamic and goal-oriented individual, our sales team is looking for you. As a sales representative, you'll be responsible for building and maintaining relationships with clients, identifying sales opportunities, and promoting our products and services. Join our team and contribute to our continued success in the market.",
      type: "Full-time",
      department: "Sales",
      location: "On-site",
      experienceLevel: "Entry Level",
    },
    {
      title: "Human Resources Manager",
      shortDescription: "Manage our HR department and ensure a positive work environment.",
      longDescription: "Join our HR team as a manager and play a vital role in creating a positive work environment for our employees. You'll oversee HR processes, recruit top talent, and implement HR strategies. If you have a passion for HR and want to make a difference in our company's culture, we invite you to apply.",
      type: "Full-time",
      department: "Human Resources",
      location: "Hybrid",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Data Scientist",
      shortDescription: "Analyze and extract insights from data to drive business decisions.",
      longDescription: "We're seeking a talented data scientist to join our data analytics team. You will work on data analysis, predictive modeling, and data-driven decision-making. If you have a strong analytical mindset and a passion for turning data into actionable insights, we want to hear from you.",
      type: "Full-time",
      department: "IT/Technology",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Graphic Designer",
      shortDescription: "Create stunning visual content and designs for our brand.",
      longDescription: "Join our creative team as a graphic designer and unleash your design skills to create stunning visual content for our brand. You'll be responsible for designing eye-catching graphics, illustrations, and other visual materials. If you have a passion for design and want to leave your artistic mark, we'd love to work with you.",
      type: "Contract",
      department: "Design",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Customer Support Representative",
      shortDescription: "Provide top-notch customer support and assist our clients.",
      longDescription: "Our customer support team is looking for friendly and dedicated individuals to provide top-notch assistance to our clients. As a customer support representative, you'll handle customer inquiries, resolve issues, and ensure exceptional customer satisfaction. If you have excellent communication skills and enjoy helping people, we want you on our team.",
      type: "Full-time",
      department: "Customer Service",
      location: "On-site",
      experienceLevel: "Entry Level",
    },
    {
      title: "Legal Counsel",
      shortDescription: "Ensure legal compliance and provide advice on legal matters.",
      longDescription: "Our legal department is seeking a skilled legal counsel to provide expert advice on legal matters, ensure legal compliance, and protect the interests of our company. If you have a strong legal background and are passionate about providing sound legal guidance, we invite you to join our team.",
      type: "Full-time",
      department: "Legal",
      location: "Hybrid",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Product Manager",
      shortDescription: "Lead product development and strategy for our innovative projects.",
      longDescription: "Join our product management team and lead the development and strategy of our innovative projects. You'll be responsible for defining product roadmaps, collaborating with cross-functional teams, and ensuring the successful launch of products. If you have a passion for product development and want to drive innovation, we'd like to meet you.",
      type: "Full-time",
      department: "Product Management",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Financial Analyst",
      shortDescription: "Analyze financial data to support strategic decision-making.",
      longDescription: "Our finance department is in need of a financial analyst to analyze financial data, create reports, and support strategic decision-making. If you have a strong analytical mind and a passion for finance, we encourage you to apply and contribute to our financial success.",
      type: "Full-time",
      department: "Finance",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "Content Writer",
      shortDescription: "Create engaging and informative content for our online platforms.",
      longDescription: "We're looking for a creative content writer to produce engaging and informative content for our online platforms. You'll be responsible for writing blog posts, articles, and marketing copy. If you have a way with words and a passion for content creation, we'd love to have you on our content team.",
      type: "Full-time",
      department: "Marketing",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Quality Assurance Tester",
      shortDescription: "Ensure the quality and functionality of our software products.",
      longDescription: "Join our quality assurance team as a tester and play a vital role in ensuring the quality and functionality of our software products. You'll be responsible for testing, identifying bugs, and working closely with developers to improve software quality. If you have a sharp eye for detail and a passion for software quality, we want to work with you.",
      type: "Full-time",
      department: "IT/Technology",
      location: "Hybrid",
      experienceLevel: "Entry Level",
    },
    {
      title: "Project Manager",
      shortDescription: "Lead and oversee project execution to meet business goals.",
      longDescription: "Our project management team is seeking an experienced project manager to lead and oversee project execution, ensuring projects are completed on time and within scope. If you have strong project management skills and enjoy driving projects to success, we'd like to have you on board.",
      type: "Full-time",
      department: "Operations",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "UX/UI Designer",
      shortDescription: "Design user-friendly interfaces and experiences for our products.",
      longDescription: "We're in search of a talented UX/UI designer to create user-friendly interfaces and experiences for our products. You'll be responsible for designing user interfaces that enhance the user experience. If you have a keen eye for design and are passionate about user-centric design, we encourage you to apply.",
      type: "Full-time",
      department: "Design",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Research Scientist",
      shortDescription: "Conduct research and experiments to advance our knowledge.",
      longDescription: "Join our research and development team as a research scientist to conduct experiments and advance our knowledge in your field. You'll have the opportunity to contribute to groundbreaking discoveries and innovation. If you're passionate about research and eager to make a significant impact, we'd love to have you as part of our team.",
      type: "Full-time",
      department: "Research and Development",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Administrative Assistant",
      shortDescription: "Provide administrative support and assist with office operations.",
      longDescription: "Our administrative team is looking for an administrative assistant to provide support and assist with office operations. You'll handle administrative tasks, manage office activities, and ensure smooth operations. If you have strong organizational skills and enjoy administrative work, we'd like to work with you.",
      type: "Part-time",
      department: "Administration",
      location: "On-site",
      experienceLevel: "Entry Level",
    },
    {
      title: "Intern",
      shortDescription: "Gain hands-on experience and learn from experts in the field.",
      longDescription: "Are you looking for an exciting internship opportunity to gain hands-on experience and learn from experts in the field? Our internship program offers a unique chance to work on real projects and build valuable skills. If you're a motivated student or recent graduate, we'd love to have you as part of our team.",
      type: "Internship",
      department: "Other",
      location: "Hybrid",
      experienceLevel: "Intern",
    },
    {
      title: "Customer Success Manager",
      shortDescription: "Build and maintain strong relationships with our valued clients.",
      longDescription: "Our customer success team is in search of a customer success manager to build and maintain strong relationships with our valued clients. You'll be responsible for ensuring customer satisfaction, addressing their needs, and driving their success. If you have strong relationship-building skills and are passionate about customer success, we encourage you to apply.",
      type: "Full-time",
      department: "Customer Service",
      location: "Remote",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Accountant",
      shortDescription: "Manage financial records and ensure accurate financial reporting.",
      longDescription: "Our finance department is looking for a skilled accountant to manage financial records, conduct audits, and ensure accurate financial reporting. If you have a strong financial background and enjoy working with numbers, we invite you to join our team and contribute to our financial success.",
      type: "Full-time",
      department: "Finance",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "Operations Manager",
      shortDescription: "Oversee and optimize business operations for efficiency and success.",
      longDescription: "Join our operations team as a manager and play a key role in overseeing and optimizing business operations for efficiency and success. You'll be responsible for streamlining processes, managing resources, and ensuring smooth operations. If you have strong operations management skills and enjoy driving operational excellence, we'd like to work with you.",
      type: "Full-time",
      department: "Operations",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Executive Assistant",
      shortDescription: "Provide high-level administrative support to company executives.",
      longDescription: "Our executive team is looking for an executive assistant to provide high-level administrative support and assist company executives in their roles. You'll manage executive schedules, handle confidential information, and ensure smooth operations. If you have strong organizational skills and enjoy working at the executive level, we'd like to work with you.",
      type: "Full-time",
      department: "Administration",
      location: "Hybrid",
      experienceLevel: "Associate",
    },
    {
      title: "IT Support Specialist",
      shortDescription: "Provide technical support and assistance to our IT team and employees.",
      longDescription: "Our IT/Technology department is in need of an IT support specialist to provide technical support and assistance to our IT team and employees. You'll troubleshoot technical issues, set up hardware and software, and ensure smooth IT operations. If you have strong technical skills and enjoy helping others with their IT needs, we encourage you to apply.",
      type: "Full-time",
      department: "IT/Technology",
      location: "Remote",
      experienceLevel: "Entry Level",
    },
    {
      title: "Product Designer",
      shortDescription: "Design and prototype innovative products and user interfaces.",
      longDescription: "Join our product design team as a designer and take part in designing and prototyping innovative products and user interfaces. You'll be responsible for creating product designs that meet user needs and enhance their experience. If you have a passion for product design and enjoy turning ideas into reality, we'd like to work with you.",
      type: "Contract",
      department: "Design",
      location: "Hybrid",
      experienceLevel: "Associate",
    },
    {
      title: "Software Developer",
      shortDescription: "Develop software solutions to meet business and client needs.",
      longDescription: "Our software development team is seeking a talented software developer to create software solutions that meet business and client needs. You'll work on coding, debugging, and delivering high-quality software. If you have a strong programming background and enjoy developing software that makes a difference, we encourage you to apply.",
      type: "Full-time",
      department: "Engineering",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "Data Analyst",
      shortDescription: "Analyze data to provide insights and support data-driven decisions.",
      longDescription: "Our data analytics team is looking for a data analyst to analyze data, provide insights, and support data-driven decisions. You'll work on data analysis, reporting, and data visualization. If you have strong analytical skills and a passion for turning data into valuable insights, we encourage you to apply.",
      type: "Full-time",
      department: "IT/Technology",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Public Relations Specialist",
      shortDescription: "Manage public relations and communications for our brand.",
      longDescription: "Our marketing and communications team is seeking a public relations specialist to manage public relations and communications for our brand. You'll be responsible for creating PR campaigns, managing media relations, and enhancing our brand image. If you have a passion for public relations and enjoy building a positive brand image, we'd like to have you on our team.",
      type: "Full-time",
      department: "Marketing",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "Customer Experience Manager",
      shortDescription: "Optimize the customer experience and ensure customer satisfaction.",
      longDescription: "Our customer experience team is looking for a customer experience manager to optimize the customer experience and ensure customer satisfaction. You'll be responsible for creating customer-centric strategies, addressing customer needs, and driving exceptional customer experiences. If you have strong customer service skills and are passionate about customer satisfaction, we encourage you to apply.",
      type: "Full-time",
      department: "Customer Service",
      location: "Hybrid",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "HR Coordinator",
      shortDescription: "Support HR processes and assist in recruitment and employee management.",
      longDescription: "Our human resources team is seeking an HR coordinator to support HR processes, assist in recruitment, and manage employee relations. You'll be responsible for onboarding, benefits administration, and HR coordination. If you have strong organizational skills and are passionate about HR support, we'd like to work with you.",
      type: "Full-time",
      department: "Human Resources",
      location: "Remote",
      experienceLevel: "Entry Level",
    },
    {
      title: "Sales Manager",
      shortDescription: "Lead and manage the sales team to achieve revenue targets.",
      longDescription: "Our sales department is looking for a sales manager to lead and manage the sales team, set sales targets, and drive revenue growth. You'll be responsible for sales strategy, team leadership, and achieving sales goals. If you have strong sales leadership skills and are passionate about driving sales success, we encourage you to apply.",
      type: "Full-time",
      department: "Sales",
      location: "On-site",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Customer Support Specialist",
      shortDescription: "Provide expert support and solutions to our customers.",
      longDescription: "Our customer support team is seeking a customer support specialist to provide expert support and solutions to our customers. You'll handle complex customer inquiries, resolve issues, and ensure exceptional customer satisfaction. If you have strong technical support skills and enjoy delivering expert solutions, we want to work with you.",
      type: "Full-time",
      department: "Customer Service",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Legal Assistant",
      shortDescription: "Assist in legal matters and provide support to our legal team.",
      longDescription: "Our legal department is looking for a legal assistant to assist in legal matters, provide support to our legal team, and ensure legal compliance. You'll be responsible for legal research, document preparation, and administrative support. If you have strong legal skills and are passionate about supporting legal operations, we encourage you to apply.",
      type: "Part-time",
      department: "Legal",
      location: "On-site",
      experienceLevel: "Entry Level",
    },
    {
      title: "Social Media Manager",
      shortDescription: "Manage our social media presence and engage with our online community.",
      longDescription: "Our marketing team is seeking a social media manager to manage our social media presence, engage with our online community, and create compelling social media content. You'll be responsible for social media strategy, content creation, and community management. If you have strong social media skills and enjoy building an online presence, we'd like to have you on our social media team.",
      type: "Full-time",
      department: "Marketing",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Event Coordinator",
      shortDescription: "Plan and execute events and activities to engage our audience.",
      longDescription: "Our marketing team is looking for an event coordinator to plan and execute events and activities to engage our audience and promote our brand. You'll be responsible for event planning, coordination, and ensuring successful events. If you have strong event planning skills and enjoy creating memorable experiences, we encourage you to apply.",
      type: "Contract",
      department: "Marketing",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "Content Strategist",
      shortDescription: "Develop content strategies to drive brand awareness and engagement.",
      longDescription: "Our content team is seeking a content strategist to develop content strategies that drive brand awareness and engagement. You'll be responsible for content planning, strategy development, and content optimization. If you have strong content strategy skills and enjoy creating impactful content, we'd like to work with you.",
      type: "Full-time",
      department: "Marketing",
      location: "Hybrid",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "IT Security Analyst",
      shortDescription: "Protect our IT infrastructure and data from security threats.",
      longDescription: "Our IT/Technology department is in need of an IT security analyst to protect our IT infrastructure and data from security threats. You'll be responsible for security analysis, threat detection, and ensuring a secure IT environment. If you have strong security skills and are passionate about IT security, we encourage you to apply.",
      type: "Full-time",
      department: "IT/Technology",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "Customer Relations Manager",
      shortDescription: "Build and maintain strong customer relations and partnerships.",
      longDescription: "Our customer relations team is looking for a customer relations manager to build and maintain strong customer relations and partnerships. You'll be responsible for fostering positive relationships, addressing customer needs, and driving customer success. If you have strong customer relations skills and are passionate about building lasting partnerships, we'd like to work with you.",
      type: "Full-time",
      department: "Customer Service",
      location: "Remote",
      experienceLevel: "Mid-Senior Level",
    },
    {
      title: "Business Analyst",
      shortDescription: "Analyze business processes and support strategic decision-making.",
      longDescription: "Our business analysis team is in search of a business analyst to analyze business processes, provide insights, and support strategic decision-making. You'll work on process analysis, reporting, and data-driven decision support. If you have strong analytical skills and are passionate about improving business operations, we encourage you to apply.",
      type: "Full-time",
      department: "Operations",
      location: "On-site",
      experienceLevel: "Associate",
    },
    {
      title: "UX Researcher",
      shortDescription: "Conduct user research to inform the design of our digital products.",
      longDescription: "Our design team is looking for a UX researcher to conduct user research and inform the design of our digital products. You'll be responsible for user interviews, usability testing, and user-centered research. If you have strong research skills and are passionate about creating user-friendly digital experiences, we'd like to have you on our UX team.",
      type: "Full-time",
      department: "Design",
      location: "Remote",
      experienceLevel: "Associate",
    },
    {
      title: "Content Editor",
      shortDescription: "Edit and refine content to ensure accuracy and quality.",
      longDescription: "Our content team is seeking a content editor to edit and refine content to ensure accuracy and quality. You'll be responsible for proofreading, content editing, and maintaining content standards. If you have strong editing skills and are passionate about maintaining content quality, we encourage you to apply.",
      type: "Part-time",
      department: "Marketing",
      location: "On-site",
      experienceLevel: "Entry Level",
    },
    {
      title: "Sales Support Specialist",
      shortDescription: "Provide sales support and assist our sales team in achieving targets.",
      longDescription: "Our sales department is looking for a sales support specialist to provide sales support and assist our sales team in achieving targets. You'll be responsible for administrative tasks, sales coordination, and ensuring smooth sales operations. If you have strong sales support skills and are passionate about sales success, we want to work with you.",
      type: "Full-time",
      department: "Sales",
      location: "Remote",
      experienceLevel: "Entry Level",
    },
    {
      title: "Project Coordinator",
      shortDescription: "Support project execution and ensure projects are on track.",
      longDescription: "Our project management team is seeking a project coordinator to support project execution and ensure projects are on track. You'll be responsible for project coordination, task tracking, and project reporting. If you have strong project coordination skills and are passionate about project success, we'd like to have you on board.",
      type: "Full-time",
      department: "Operations",
      location: "Hybrid",
      experienceLevel: "Entry Level",
    },
    {
      title: "Legal Advisor",
      shortDescription: "Provide legal advice and support on various legal matters.",
      longDescription: "Our legal department is in need of a legal advisor to provide legal advice and support on various legal matters. You'll be responsible for legal consultation, contract review, and legal documentation. If you have strong legal advisory skills and are passionate about providing expert legal guidance, we encourage you to apply.",
      type: "Full-time",
      department: "Legal",
      location: "On-site",
      experienceLevel: "Associate",
    },
  ];
  
  module.exports = sampleJobs;
  